site_name: Project 1 Documentation
site_url: 'https://bellandi.github.io/documentation/project1'
#repo_url: https://github.com/bellandi/documentation/tree/main/project1
use_directory_urls: false
extra:
  version:
    provider: mike
theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.path
    - navigation.sections
    - search.suggest
    - search.highlight
  plugins:
    - offline
markdown_extensions:
  - admonition
  - attr_list
 # - pymdownx.emoji:
 #     emoji_index: !!python/name:material.extensions.emoji.twemoji
 #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home Project1: index.md
  - Test1 Project1: test.md
  - Test2 Project1: test2.md
