site_name: Project 2 Documentation
site_url: 'https://bellandi.github.io/documentation/project2'
#repo_url: https://github.com/bellandi/documentation/tree/main/project2
use_directory_urls: false
extra:
  version:
    provider: mike
theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.path
    - navigation.sections
    - search.suggest
    - search.highlight
  plugins:
    - offline
markdown_extensions:
  - admonition
  - attr_list
 # - pymdownx.emoji:
 #     emoji_index: !!python/name:material.extensions.emoji.twemoji
 #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home Project2: index.md
  - Test1 Project2: test.md
  - Test2 Project2: test2.md
