name: Deploy Common Documentation With MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs and dependencies
      run: |
        pip install mkdocs
        pip install mkdocs-material

    - name: Build the MkDocs site
      run: |
        cd common
        mkdocs build

    - name: Configure Git Credentials
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages

    - name: Copy new site files to gh-pages, merging with existing content
      run: |
        cp -r common/site/* .
        rm -rf common/site

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update common documentation"
        git push origin gh-pages
